services:
  write-db:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
  read-db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGODB_DATABASE="vf-read-db"
