services:
  write-db:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
  read-db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGODB_DATABASE="vf-read-db"
  event-store:
    image: mongo:6.0.4
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
